## TensorFlow로 알아보는 딥러닝

In [ ]:
import tensorflow as tf
import pandas as pd

In [ ]:
data = {
    '창업연차' : [4, 5, 6, 7, 8],
    '매출액(억)' : [8, 10, 12, 14, 16]
}

df = pd.DataFrame(data)
df

창업연차  매출액(억)
0     4       8
1     5      10
2     6      12
3     7      14
4     8      16

In [ ]:
독립 = df[['창업연차']] # 원인
종속 = df[['매출액(억)']] # 결과

독립.shape, 종속.shape

((5, 1), (5, 1))

In [ ]:
## 모델 준비
## 신경망 -> y = wx + b
X = tf.keras.layers.Input(shape=[1]) # 독립변수의 col
Y = tf.keras.layers.Dense(1)(X) # 종속변수의 col
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse') 
#MSE(mean squared error) : 회귀 용도의 딥러닝 모델을 훈련시킬 때 사용되는 손실 함수

In [ ]:
model.fit(독립, 종속, epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 488ms/step - loss: 436.5558
Epoch 2/10
1/1 [==============================] - 0s 3ms/step - loss: 435.6130
Epoch 3/10
1/1 [==============================] - 0s 5ms/step - loss: 434.9302
Epoch 4/10
1/1 [==============================] - 0s 4ms/step - loss: 434.3589
Epoch 5/10
1/1 [==============================] - 0s 4ms/step - loss: 433.8522
Epoch 6/10
1/1 [==============================] - 0s 4ms/step - loss: 433.3883
Epoch 7/10
1/1 [==============================] - 0s 4ms/step - loss: 432.9549
Epoch 8/10
1/1 [==============================] - 0s 4ms/step - loss: 432.5444
Epoch 9/10
1/1 [==============================] - 0s 4ms/step - loss: 432.1517
Epoch 10/10
1/1 [==============================] - 0s 4ms/step - loss: 431.7733


In [ ]:
model.predict([10])

array([[-13.703943]], dtype=float32)

In [ ]:
model.predict(독립)

array([[ -5.4711885],
       [ -6.843314 ],
       [ -8.215441 ],
       [ -9.587566 ],
       [-10.959692 ]], dtype=float32)

In [ ]:
#y = wx + b

model.get_weights()

[array([[-1.3721259]], dtype=float32), array([0.01731501], dtype=float32)]

In [ ]:
-1.3721259 * 10 + 0.01731501

-13.703943989999999

In [ ]:
model.fit(독립, 종속, epochs=10000, verbose=0)
model.fit(독립, 종속, epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 4ms/step - loss: 1.2750e-05
Epoch 2/10
1/1 [==============================] - 0s 4ms/step - loss: 1.2749e-05
Epoch 3/10
1/1 [==============================] - 0s 5ms/step - loss: 1.2750e-05
Epoch 4/10
1/1 [==============================] - 0s 5ms/step - loss: 1.2749e-05
Epoch 5/10
1/1 [==============================] - 0s 5ms/step - loss: 1.2750e-05
Epoch 6/10
1/1 [==============================] - 0s 5ms/step - loss: 1.2749e-05
Epoch 7/10
1/1 [==============================] - 0s 5ms/step - loss: 1.2750e-05
Epoch 8/10
1/1 [==============================] - 0s 5ms/step - loss: 1.2749e-05
Epoch 9/10
1/1 [==============================] - 0s 4ms/step - loss: 1.2750e-05
Epoch 10/10
1/1 [==============================] - 0s 5ms/step - loss: 1.2749e-05


In [ ]:
model.predict([10])

array([[19.994501]], dtype=float32)

In [ ]:
model.predict(독립)

array([[ 7.9975004],
       [ 9.997001 ],
       [11.9965   ],
       [13.995999 ],
       [15.9955   ]], dtype=float32)

In [ ]:
#y = wx + b

model.get_weights()

[array([[1.9994998]], dtype=float32), array([-0.00049862], dtype=float32)]

In [ ]:
1.9994998 * 10 + (-0.00049862)

19.99449938

In [1]:
import tensorflow as tf
import pandas as pd

In [2]:
from sklearn import datasets

iris = datasets.load_iris()
iris

{'DESCR': '.. _iris_dataset:\n\nIris plants dataset\n--------------------\n\n**Data Set Characteristics:**\n\n    :Number of Instances: 150 (50 in each of three classes)\n    :Number of Attributes: 4 numeric, predictive attributes and the class\n    :Attribute Information:\n        - sepal length in cm\n        - sepal width in cm\n        - petal length in cm\n        - petal width in cm\n        - class:\n                - Iris-Setosa\n                - Iris-Versicolour\n                - Iris-Virginica\n                \n    :Summary Statistics:\n\n    ============== ==== ==== ======= ===== ====================\n                    Min  Max   Mean    SD   Class Correlation\n    ============== ==== ==== ======= ===== ====================\n    sepal length:   4.3  7.9   5.84   0.83    0.7826\n    sepal width:    2.0  4.4   3.05   0.43   -0.4194\n    petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)\n    petal width:    0.1  2.5   1.20   0.76    0.9565  (high!)\n    ===========

In [3]:
# 생활코딩의 이숙번님께서 가공해주신 코드
path = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'

dataset = pd.read_csv(path)
dataset.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [4]:
dataset

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭         품종
0     5.1  3.5    1.4   0.2     setosa
1     4.9  3.0    1.4   0.2     setosa
2     4.7  3.2    1.3   0.2     setosa
3     4.6  3.1    1.5   0.2     setosa
4     5.0  3.6    1.4   0.2     setosa
..    ...  ...    ...   ...        ...
145   6.7  3.0    5.2   2.3  virginica
146   6.3  2.5    5.0   1.9  virginica
147   6.5  3.0    5.2   2.0  virginica
148   6.2  3.4    5.4   2.3  virginica
149   5.9  3.0    5.1   1.8  virginica

[150 rows x 5 columns]

In [5]:
encoded = pd.get_dummies(dataset)
encoded.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [6]:
print(encoded.columns)

독립 = encoded[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = encoded[['품종_setosa', '품종_versicolor', '품종_virginica']]

독립.shape, 종속.shape

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')


((150, 4), (150, 3))

In [7]:
## 모델 준비

X = tf.keras.layers.Input(shape=[4]) # 독립변수의 col
Y = tf.keras.layers.Dense(3, activation='softmax')(X) # 종속변수의 col
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

* fit
* predict

In [8]:
## 모델 학습
model.fit(독립, 종속, epochs=1000, verbose=0) # epochs는 학습 수
model.fit(독립, 종속, epochs=10) # epochs는 학습 수

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1535 - accuracy: 0.9800
Epoch 2/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1539 - accuracy: 0.9800
Epoch 3/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1530 - accuracy: 0.9800
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1530 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 1ms/step - loss: 0.1529 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1525 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1525 - accuracy: 0.9800
Epoch 8/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1532 - accuracy: 0.9867
Epoch 9/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1520 - accuracy: 0.9800
Epoch 10/10
5/5 [==============================] - 0s 2ms/step - loss: 0.1524 - accuracy: 0.9800


In [10]:
model.predict(독립)

array([[9.99176323e-01, 8.23636015e-04, 4.78683795e-08],
       [9.95592177e-01, 4.40731505e-03, 5.34042101e-07],
       [9.98422742e-01, 1.57718710e-03, 1.70014118e-07],
       [9.96045053e-01, 3.95424385e-03, 7.70751853e-07],
       [9.99428451e-01, 5.71494049e-04, 3.43467157e-08],
       [9.99096751e-01, 9.03157983e-04, 7.58436514e-08],
       [9.98650253e-01, 1.34948478e-03, 2.20135902e-07],
       [9.98466015e-01, 1.53385277e-03, 1.34099224e-07],
       [9.94407535e-01, 5.59101999e-03, 1.41983458e-06],
       [9.96733546e-01, 3.26614268e-03, 3.22901116e-07],
       [9.99405861e-01, 5.94098703e-04, 2.32966091e-08],
       [9.98017669e-01, 1.98204559e-03, 2.69553539e-07],
       [9.96652782e-01, 3.34689580e-03, 3.44479588e-07],
       [9.98769104e-01, 1.23071496e-03, 1.38943378e-07],
       [9.99906182e-01, 9.37926670e-05, 9.49798684e-10],
       [9.99905467e-01, 9.45291249e-05, 2.31637198e-09],
       [9.99726713e-01, 2.73278914e-04, 1.09920428e-08],
       [9.98937070e-01, 1.06281

In [11]:
model.predict([[5.1, 3.5, 1.4, 0.2]])

array([[9.9917632e-01, 8.2363596e-04, 4.7868376e-08]], dtype=float32)

In [12]:
model.get_weights()

[array([[ 1.0424904 ,  1.2535572 , -0.03552704],
        [ 3.469206  ,  0.02300576, -0.9308156 ],
        [-3.2388396 , -0.24875134,  1.5914913 ],
        [-3.7681313 , -1.2162236 ,  1.7049367 ]], dtype=float32),
 array([ 2.0939665,  1.2817637, -1.7191325], dtype=float32)]

## 히든레이어

In [19]:
import pandas as pd
import tensorflow as tf

In [13]:
data = {
    '창업연차' : [4, 5, 6, 7, 8],
    '직원수' : [10, 20, 30, 40, 50],
    '기업가치' : [80, 200, 360, 540, 800]
}

df = pd.DataFrame(data)
df

창업연차  직원수  기업가치
0     4   10    80
1     5   20   200
2     6   30   360
3     7   40   540
4     8   50   800

In [15]:
9 * 60 * 2
8 * 50 * 2

800

In [17]:
독립 = df[['창업연차', '직원수']]
종속 = df[['기업가치']]

독립.shape, 종속.shape

((5, 2), (5, 1))

In [18]:
## 모델 준비
X = tf.keras.layers.Input(shape=[2]) # 독립변수의 col
Y = tf.keras.layers.Dense(1)(X) # 종속변수의 col
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [26]:
## 모델 학습
model.fit(독립, 종속, epochs=100000, verbose=0) # epochs는 학습 수
model.fit(독립, 종속, epochs=10) # epochs는 학습 수

Epoch 1/10
1/1 [==============================] - 0s 4ms/step - loss: 1336.0006
Epoch 2/10
1/1 [==============================] - 0s 4ms/step - loss: 1336.0007
Epoch 3/10
1/1 [==============================] - 0s 3ms/step - loss: 1336.0006
Epoch 4/10
1/1 [==============================] - 0s 9ms/step - loss: 1336.0007
Epoch 5/10
1/1 [==============================] - 0s 5ms/step - loss: 1336.0006
Epoch 6/10
1/1 [==============================] - 0s 4ms/step - loss: 1336.0007
Epoch 7/10
1/1 [==============================] - 0s 5ms/step - loss: 1336.0006
Epoch 8/10
1/1 [==============================] - 0s 7ms/step - loss: 1336.0007
Epoch 9/10
1/1 [==============================] - 0s 4ms/step - loss: 1336.0006
Epoch 10/10
1/1 [==============================] - 0s 2ms/step - loss: 1336.0007


In [25]:
model.predict(독립)

array([[ 40.00759],
       [218.01305],
       [396.0185 ],
       [574.024  ],
       [752.0294 ]], dtype=float32)

In [29]:
model.predict(독립)

array([[ 40.00759],
       [218.01305],
       [396.0185 ],
       [574.024  ],
       [752.0294 ]], dtype=float32)

In [30]:
## 모델 준비
X = tf.keras.layers.Input(shape=[2]) # 독립변수의 col
H = tf.keras.layers.Dense(10, activation='swish')(X)
H = tf.keras.layers.Dense(10, activation='swish')(H)
H = tf.keras.layers.Dense(10, activation='swish')(H)
Y = tf.keras.layers.Dense(1)(H) # 종속변수의 col
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [31]:
## 모델 학습
model.fit(독립, 종속, epochs=100000, verbose=0) # epochs는 학습 수
model.fit(독립, 종속, epochs=10) # epochs는 학습 수

Epoch 1/10
1/1 [==============================] - 0s 4ms/step - loss: 2.9364
Epoch 2/10
1/1 [==============================] - 0s 6ms/step - loss: 2.9913
Epoch 3/10
1/1 [==============================] - 0s 4ms/step - loss: 3.2849
Epoch 4/10
1/1 [==============================] - 0s 4ms/step - loss: 3.3404
Epoch 5/10
1/1 [==============================] - 0s 5ms/step - loss: 3.4185
Epoch 6/10
1/1 [==============================] - 0s 3ms/step - loss: 3.3438
Epoch 7/10
1/1 [==============================] - 0s 4ms/step - loss: 3.3808
Epoch 8/10
1/1 [==============================] - 0s 5ms/step - loss: 3.3164
Epoch 9/10
1/1 [==============================] - 0s 4ms/step - loss: 3.2260
Epoch 10/10
1/1 [==============================] - 0s 5ms/step - loss: 3.1628


In [32]:
model.predict(독립)

array([[ 80.55703],
       [201.30109],
       [362.26923],
       [541.92065],
       [802.21185]], dtype=float32)

In [33]:
model.predict([[9, 60]])

array([[971.6316]], dtype=float32)

In [34]:
model.get_weights()

[array([[ 0.75911945,  1.1343637 ,  0.08391015,  0.6134996 , -0.11543693,
         -0.76582396,  0.8819028 ,  0.48899165, -0.11505637, -1.4400626 ],
        [-0.16695927, -0.22369613,  0.44612536, -0.15080552,  0.9968465 ,
          0.57317275, -0.25148797,  0.6504851 ,  0.00562786,  0.71707547]],
       dtype=float32),
 array([ 1.2311378 ,  0.9343593 ,  0.04395708,  1.6834301 , -0.69349587,
        -1.2895297 ,  0.31865025, -0.11727212,  0.5673323 , -1.6838378 ],
       dtype=float32),
 array([[ 8.08377624e-01,  8.21109533e-01,  1.50204003e-01,
         -5.41574001e-01,  1.10583580e+00, -1.31281483e+00,
         -1.25764573e+00, -8.86196041e+00, -4.95811850e-01,
          1.12742484e+00],
        [ 1.05549312e+00,  7.46800900e-01,  6.92513764e-01,
         -8.37019444e-01,  1.07649267e+00, -1.50832772e+00,
         -8.08406949e-01, -6.96664476e+00,  3.40517759e-01,
          1.54365361e-01],
        [-2.76513547e-01, -1.59810893e-02, -2.53848284e-01,
          8.22523177e-01,  5.96847

## 오름데이터 추천

In [37]:
df = pd.read_csv('test.csv', encoding='utf-8')
df

name  loc  men  women  age
0       송악산    0   56     44   30
1      물영아리    0   54     46   20
2       이승이    0   61     39   30
3     머체왓숲길    0   47     53   50
4     성산일출봉    0   63     37   20
5        군산    0   65     35   30
6       용머리    0   59     41   20
7     따라비오름    0   56     44   30
8       영주산    0   49     51   30
9     백약이오름    0   42     58   20
10     붉은오름    0   50     50   30
11      고근산    0   50     50   50
12     거문오름    1   50     50   30
13     검은오름    1   46     54   20
14     궷물오름    1   54     46   20
15      다랑쉬    1   54     46   20
16      도두봉    1   48     52   20
17  물메(수산봉)    1   53     47   20
18      민오름    1   47     53   20
19   큰바리메오름    1   64     36   50
20     붉은오름    1   50     50   30
21     산굼부리    1   54     46   20
22     새별오름    1   50     50   20
23      서우봉    1   49     51   20
24      수월봉    1   55     45   20
25    아끈다랑쉬    1   50     50   30
26     아부오름    1   44     56   20
27     안돌오름    1   58     42   20
28    용눈이오름    1   42     58   20
29     저지오름    1   56     44   50
30     정물오름    1   62     38   40
31      지미봉    1   56     44   20

In [38]:
encoded = pd.get_dummies(df)
encoded.head()

loc  men  women  age  ...  name_저지오름  name_정물오름  name_지미봉  name_큰바리메오름
0    0   56     44   30  ...          0          0         0            0
1    0   54     46   20  ...          0          0         0            0
2    0   61     39   30  ...          0          0         0            0
3    0   47     53   50  ...          0          0         0            0
4    0   63     37   20  ...          0          0         0            0

[5 rows x 35 columns]

In [39]:
print(encoded.columns)

Index(['loc', 'men', 'women', 'age', 'name_거문오름', 'name_검은오름', 'name_고근산',
       'name_군산', 'name_궷물오름', 'name_다랑쉬', 'name_도두봉', 'name_따라비오름',
       'name_머체왓숲길', 'name_물메(수산봉)', 'name_물영아리', 'name_민오름', 'name_백약이오름',
       'name_붉은오름', 'name_산굼부리', 'name_새별오름', 'name_서우봉', 'name_성산일출봉',
       'name_송악산', 'name_수월봉', 'name_아끈다랑쉬', 'name_아부오름', 'name_안돌오름',
       'name_영주산', 'name_용눈이오름', 'name_용머리', 'name_이승이', 'name_저지오름',
       'name_정물오름', 'name_지미봉', 'name_큰바리메오름'],
      dtype='object')


In [40]:
독립 = encoded[['loc', 'men', 'women', 'age']]
종속 = encoded[['name_거문오름', 'name_검은오름', 'name_고근산',
       'name_군산', 'name_궷물오름', 'name_다랑쉬', 'name_도두봉', 'name_따라비오름',
       'name_머체왓숲길', 'name_물메(수산봉)', 'name_물영아리', 'name_민오름', 'name_백약이오름',
       'name_붉은오름', 'name_산굼부리', 'name_새별오름', 'name_서우봉', 'name_성산일출봉',
       'name_송악산', 'name_수월봉', 'name_아끈다랑쉬', 'name_아부오름', 'name_안돌오름',
       'name_영주산', 'name_용눈이오름', 'name_용머리', 'name_이승이', 'name_저지오름',
       'name_정물오름', 'name_지미봉', 'name_큰바리메오름']]

In [41]:
독립.shape, 종속.shape

((32, 4), (32, 31))

In [42]:
## 모델 준비

X = tf.keras.layers.Input(shape=[4]) # 독립변수의 col
Y = tf.keras.layers.Dense(31, activation='softmax')(X) # 종속변수의 col
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [43]:
## 모델 학습
model.fit(독립, 종속, epochs=100000, verbose=0) # epochs는 학습 수
model.fit(독립, 종속, epochs=10) # epochs는 학습 수

Epoch 1/10
1/1 [==============================] - 0s 4ms/step - loss: 0.3130 - accuracy: 0.8438
Epoch 2/10
1/1 [==============================] - 0s 7ms/step - loss: 0.3130 - accuracy: 0.8438
Epoch 3/10
1/1 [==============================] - 0s 4ms/step - loss: 0.3131 - accuracy: 0.8438
Epoch 4/10
1/1 [==============================] - 0s 4ms/step - loss: 0.3132 - accuracy: 0.8438
Epoch 5/10
1/1 [==============================] - 0s 4ms/step - loss: 0.3132 - accuracy: 0.8438
Epoch 6/10
1/1 [==============================] - 0s 4ms/step - loss: 0.3131 - accuracy: 0.8438
Epoch 7/10
1/1 [==============================] - 0s 3ms/step - loss: 0.3130 - accuracy: 0.8438
Epoch 8/10
1/1 [==============================] - 0s 4ms/step - loss: 0.3130 - accuracy: 0.8438
Epoch 9/10
1/1 [==============================] - 0s 3ms/step - loss: 0.3129 - accuracy: 0.8438
Epoch 10/10
1/1 [==============================] - 0s 4ms/step - loss: 0.3130 - accuracy: 0.8438


In [44]:
model.predict([[0, 56, 44, 30]])

array([[2.26821353e-08, 0.00000000e+00, 6.75464242e-13, 4.95504802e-34,
        9.11440875e-05, 9.27028232e-05, 2.62336657e-27, 5.32247066e-01,
        0.00000000e+00, 1.20902821e-09, 9.22725119e-10, 0.00000000e+00,
        0.00000000e+00, 2.93632562e-04, 6.71684684e-05, 5.38215848e-13,
        4.55157166e-19, 4.09642424e-34, 4.66907024e-01, 1.96813693e-04,
        2.05273576e-08, 0.00000000e+00, 2.77683381e-22, 0.00000000e+00,
        0.00000000e+00, 5.63797009e-09, 3.14419317e-08, 3.84104073e-15,
        1.33087301e-08, 1.04394116e-04, 2.96750420e-37]], dtype=float32)

In [47]:
model.predict([[0, 60, 40, 40]])

array([[0.0000000e+00, 0.0000000e+00, 1.1217622e-26, 2.0094495e-15,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 5.0221698e-36,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00, 1.1189866e-37, 4.6765006e-36, 6.5454897e-31,
        0.0000000e+00, 0.0000000e+00, 2.8011157e-23, 0.0000000e+00,
        0.0000000e+00, 9.4089613e-27, 1.9056850e-05, 1.0515195e-14,
        9.9998093e-01, 8.1617808e-19, 1.4173987e-08]], dtype=float32)

In [48]:
result_predict = model.predict([[0, 60, 40, 50]])[0]
result_name = ['name_거문오름',
       'name_검은오름', 'name_고근산', 'name_군산', 'name_궷물오름', 'name_다랑쉬', 'name_도두봉',
       'name_따라비오름', 'name_물메(수산봉)', 'name_물영아리', 'name_민오름', 'name_백약이오름',
       'name_붉은오름', 'name_산굼부리', 'name_새별오름', 'name_서우봉', 'name_성산일출봉',
       'name_송악산', 'name_수월봉', 'name_아끈다랑쉬', 'name_아부오름', 'name_안돌오름',
       'name_영주산', 'name_용눈이오름', 'name_용머리', 'name_이승이', 'name_저지오름',
       'name_정물오름', 'name_지미봉', 'name_큰바리메오름']

result = list(zip(result_predict*100, result_name))
result

[(0.0, 'name_거문오름'),
 (0.0, 'name_검은오름'),
 (4.4019e-29, 'name_고근산'),
 (0.0, 'name_군산'),
 (0.0, 'name_궷물오름'),
 (0.0, 'name_다랑쉬'),
 (0.0, 'name_도두봉'),
 (0.0, 'name_따라비오름'),
 (0.0, 'name_물메(수산봉)'),
 (0.0, 'name_물영아리'),
 (0.0, 'name_민오름'),
 (0.0, 'name_백약이오름'),
 (0.0, 'name_붉은오름'),
 (0.0, 'name_산굼부리'),
 (0.0, 'name_새별오름'),
 (0.0, 'name_서우봉'),
 (0.0, 'name_성산일출봉'),
 (0.0, 'name_송악산'),
 (0.0, 'name_수월봉'),
 (0.0, 'name_아끈다랑쉬'),
 (0.0, 'name_아부오름'),
 (0.0, 'name_안돌오름'),
 (0.0, 'name_영주산'),
 (0.0, 'name_용눈이오름'),
 (0.0, 'name_용머리'),
 (0.0, 'name_이승이'),
 (1.1626521e-35, 'name_저지오름'),
 (6.562089e-14, 'name_정물오름'),
 (2.8202924e-09, 'name_지미봉'),
 (0.0, 'name_큰바리메오름')]

In [50]:
def 제곱(x):
    return x**2

제곱람다 = lambda x:x**2
제곱람다(10)

100

In [52]:
test = [('일하나', 34, 100, 68),
        ('이하나', 84, 32, 32),
        ('삼하나', 54, 48, 78),
        ('사하나', 97, 91, 21),
        ('오하나', 92, 84, 11)]

In [55]:
sorted(test, key=lambda x:x[2])

[('이하나', 84, 32, 32),
 ('삼하나', 54, 48, 78),
 ('오하나', 92, 84, 11),
 ('사하나', 97, 91, 21),
 ('일하나', 34, 100, 68)]

In [59]:
result = sorted(result, key=lambda x:x[0], reverse=True)

In [58]:
result[0][1][5:]

'거문오름'

In [61]:
추천리스트 = []
for i in range(5):
    추천리스트.append(result[i][1][5:])

추천리스트

['지미봉', '정물오름', '고근산', '저지오름', '거문오름']

In [62]:
result

[(2.8202924e-09, 'name_지미봉'),
 (6.562089e-14, 'name_정물오름'),
 (4.4019e-29, 'name_고근산'),
 (1.1626521e-35, 'name_저지오름'),
 (0.0, 'name_거문오름'),
 (0.0, 'name_검은오름'),
 (0.0, 'name_군산'),
 (0.0, 'name_궷물오름'),
 (0.0, 'name_다랑쉬'),
 (0.0, 'name_도두봉'),
 (0.0, 'name_따라비오름'),
 (0.0, 'name_물메(수산봉)'),
 (0.0, 'name_물영아리'),
 (0.0, 'name_민오름'),
 (0.0, 'name_백약이오름'),
 (0.0, 'name_붉은오름'),
 (0.0, 'name_산굼부리'),
 (0.0, 'name_새별오름'),
 (0.0, 'name_서우봉'),
 (0.0, 'name_성산일출봉'),
 (0.0, 'name_송악산'),
 (0.0, 'name_수월봉'),
 (0.0, 'name_아끈다랑쉬'),
 (0.0, 'name_아부오름'),
 (0.0, 'name_안돌오름'),
 (0.0, 'name_영주산'),
 (0.0, 'name_용눈이오름'),
 (0.0, 'name_용머리'),
 (0.0, 'name_이승이'),
 (0.0, 'name_큰바리메오름')]